### ISSUE TITLE
npm run dev:server报错

### ISSUE THREAD

**Issue by cooper1x** [serverless-plus/photo-album#1]
# 描述
我按照文档操作，执行npm run dev:server的时候，先是出现 ts-node 报错。
于是我安装了 ts-node，重复执行命令，出现以下报错：
```
➜ npm run dev:server  

> photo-album@0.1.0 dev:server
> NODE_ENV=development ts-node src/server.ts

(node:10467) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
(Use `node --trace-deprecation ...` to show where the warning was created)
[Sequelize] Try to create database photo-album
ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:5432
    at ConnectionManager.connect (/Users/cooper/github_project/photo-album/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:116:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ConnectionManager._connect (/Users/cooper/github_project/photo-album/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
    at /Users/cooper/github_project/photo-album/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
    at ConnectionManager.getConnection (/Users/cooper/github_project/photo-album/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
    at /Users/cooper/github_project/photo-album/node_modules/sequelize/lib/sequelize.js:613:26
    at Object.initDatabase (/Users/cooper/github_project/photo-album/src/sequelize.ts:42:7)
    at initServer (/Users/cooper/github_project/photo-album/src/server.ts:12:3) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5432,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5432,
    fatal: true
  }
}
  App is running at http://localhost:3000 in development mode
  Press CTRL-C to stop
```
而 docker 的 dashboard 里面，mysql 是红色未启动状态。
![image](https://user-images.githubusercontent.com/9080789/117760838-edb72100-b258-11eb-9b1d-163c83dc7fd0.png)

## 环境
macOS bigsur
nodejs 16.1.0
npm 7.12.1

**Comment by yugasun** [comment]
首先，请确保mysql 已经在本地正常启动
然后，请确定 .env 中配置的链接数据库的端口变量 `PORT` 为 `3306`，从报错中看配置的是 `5432`，而 mysql 通常链接端口为 `3306`
